"""add_transformations_table

Revision ID: 26ac1d365ec3
Revises: d972055a75bd
Create Date: 2026-07-15 10:40:34.556526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ac1d365ec3'
down_revision: Union[str, None] = 'd972055a75bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_cn', sa.String(length=100), nullable=False),
    sa.Column('items_needed', sa.Integer(), nullable=False, comment='需要几个道具触发'),
    sa.Column('required_items', sa.JSON(), nullable=False, comment='所需道具列表'),
    sa.Column('effect', sa.Text(), nullable=True, comment='套装效果描述'),
    sa.Column('item_pools', sa.JSON(), nullable=True, comment='道具池'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformations')
    # ### end Alembic commands ###
