"""add_guides_table

Revision ID: 45f87b3b9dab
Revises: 08976f428d84
Create Date: 2026-07-16 15:12:04.022702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f87b3b9dab'
down_revision: Union[str, None] = '08976f428d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='正文（Markdown）'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者 ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='item / character / ending / general'),
    sa.Column('related_item_id', sa.Integer(), nullable=True, comment='关联道具'),
    sa.Column('related_character_id', sa.Integer(), nullable=True, comment='关联角色'),
    sa.Column('related_ending_id', sa.Integer(), nullable=True, comment='关联结局'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['related_ending_id'], ['endings.id'], ),
    sa.ForeignKeyConstraint(['related_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guides')
    # ### end Alembic commands ###
