"""fix quality to TINYINT

Revision ID: 6f7512d50b5f
Revises: f38cb977c006
Create Date: 2026-07-13 10:49:19.223106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f7512d50b5f'
down_revision: Union[str, None] = 'f38cb977c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'quality',
               existing_type=mysql.INTEGER(),
               type_=mysql.TINYINT(),
               existing_comment='品质 0-4',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'quality',
               existing_type=mysql.TINYINT(),
               type_=mysql.INTEGER(),
               existing_comment='品质 0-4',
               existing_nullable=True)
    # ### end Alembic commands ###
