"""add_endings_table

Revision ID: 74ec38e1d111
Revises: f154ff715828
Create Date: 2026-07-13 15:21:42.710513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ec38e1d111'
down_revision: Union[str, None] = 'f154ff715828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False, comment='英文名'),
    sa.Column('name_cn', sa.String(length=100), nullable=False, comment='中文名'),
    sa.Column('ending_number', sa.Integer(), nullable=False, comment='结局编号（游戏内编号 1-22+）'),
    sa.Column('completion_method', sa.Text(), nullable=False, comment='完成方式（如「击败 Mega Satan」）'),
    sa.Column('unlock_method', sa.Text(), nullable=True, comment='解锁该结局区域的条件'),
    sa.Column('required_character', sa.String(length=50), nullable=True, comment='是否强制某一角色（NULL 表示不强制）'),
    sa.Column('boss_name', sa.String(length=100), nullable=False, comment='最终 Boss 名称'),
    sa.Column('unlocks', sa.JSON(), nullable=True, comment='完成后解锁的内容（角色/道具名称数组）'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='结局画面图片路径'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endings')
    # ### end Alembic commands ###
