"""add_comments_table

Revision ID: 95066bf0ae3d
Revises: c9a570ba2d76
Create Date: 2026-07-16 15:29:30.275029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95066bf0ae3d'
down_revision: Union[str, None] = 'c9a570ba2d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False, comment='所属攻略 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评论者 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
