"""change_character_stats_to_varchar

Revision ID: ab12d8b22ecf
Revises: 26ac1d365ec3
Create Date: 2026-07-15 13:52:59.654130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab12d8b22ecf'
down_revision: Union[str, None] = '26ac1d365ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'damage',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               type_=sa.String(length=50),
               existing_comment='初始攻击力',
               existing_nullable=True)
    op.alter_column('characters', 'speed',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               type_=sa.String(length=50),
               existing_comment='初始速度',
               existing_nullable=True)
    op.alter_column('characters', 'tears',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               type_=sa.String(length=50),
               existing_comment='初始射速',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'tears',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=4, scale=2),
               existing_comment='初始射速',
               existing_nullable=True)
    op.alter_column('characters', 'speed',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=4, scale=2),
               existing_comment='初始速度',
               existing_nullable=True)
    op.alter_column('characters', 'damage',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=4, scale=2),
               existing_comment='初始攻击力',
               existing_nullable=True)
    # ### end Alembic commands ###
