"""add_stat_changes_to_items

Revision ID: d972055a75bd
Revises: 74ec38e1d111
Create Date: 2026-07-14 17:01:53.401823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd972055a75bd'
down_revision: Union[str, None] = '74ec38e1d111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stat_changes', sa.JSON(), nullable=True, comment='属性变化列表 [[属性, 数值], ...]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stat_changes')
    # ### end Alembic commands ###
