"""add characters table

Revision ID: f154ff715828
Revises: 6f7512d50b5f
Create Date: 2026-07-13 14:07:48.591099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f154ff715828'
down_revision: Union[str, None] = '6f7512d50b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('name_cn', sa.String(length=50), nullable=False),
    sa.Column('is_tainted', sa.Boolean(), nullable=False, comment='是否为里角色'),
    sa.Column('base_character_id', sa.Integer(), nullable=True, comment='里角色对应的表角色 ID'),
    sa.Column('health', sa.String(length=50), nullable=False, comment='初始生命值'),
    sa.Column('damage', sa.Numeric(precision=4, scale=2), nullable=True, comment='初始攻击力'),
    sa.Column('speed', sa.Numeric(precision=4, scale=2), nullable=True, comment='初始速度'),
    sa.Column('tears', sa.Numeric(precision=4, scale=2), nullable=True, comment='初始射速'),
    sa.Column('starting_items', sa.JSON(), nullable=True, comment='初始携带道具 ID 数组'),
    sa.Column('unlock_method', sa.Text(), nullable=True, comment='解锁方式'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色特性描述'),
    sa.Column('suitable_items', sa.JSON(), nullable=True, comment='适合道具 ID 数组'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='图片路径'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
