"""add items table

Revision ID: f38cb977c006
Revises: 
Create Date: 2026-07-13 10:48:40.333773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38cb977c006'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_cn', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='active / passive / trinket / card / pill'),
    sa.Column('quality', sa.Integer(), nullable=True, comment='品质 0-4'),
    sa.Column('description', sa.Text(), nullable=False, comment='功能描述'),
    sa.Column('effect', sa.Text(), nullable=True, comment='具体效果机制'),
    sa.Column('unlock_method', sa.Text(), nullable=True, comment='解锁方式'),
    sa.Column('suitable_characters', sa.JSON(), nullable=True, comment='适合角色 ID 数组'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='图片路径'),
    sa.Column('pick_up_text', sa.String(length=255), nullable=True, comment='拾取文字'),
    sa.Column('recharge_time', sa.String(length=50), nullable=True, comment='充能时间（仅主动道具）'),
    sa.Column('item_pools', sa.JSON(), nullable=True, comment='道具池列表'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
